import 'dart:io';
import 'package:csv/csv.dart';
import 'dart:convert';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../../models/album_model.dart';

/// Export format types.
enum ExportFormat { json, csv, pdf }

/// Service for exporting album collections to various formats.
class ExportService {
  /// Export collection to the specified format.
  /// Returns the file path of the exported file.
  Future<String> exportCollection(
    List<Album> albums,
    ExportFormat format,
  ) async {
    switch (format) {
      case ExportFormat.json:
        return _exportJson(albums);
      case ExportFormat.csv:
        return _exportCsv(albums);
      case ExportFormat.pdf:
        return _exportPdf(albums);
    }
  }

  /// Export and share directly.
  Future<void> exportAndShare(List<Album> albums, ExportFormat format) async {
    final path = await exportCollection(albums, format);
    await Share.shareXFiles(
      [XFile(path)],
      subject: 'Album Collection (\${format.name.toUpperCase()})',
    );
  }

  // ==========================================
  // JSON Export
  // ==========================================

  Future<String> _exportJson(List<Album> albums) async {
    final data = {
      'exportDate': DateTime.now().toIso8601String(),
      'totalAlbums': albums.length,
      'albums': albums.map((a) => _albumToMap(a)).toList(),
    };

    final jsonString = JsonEncoder.withIndent('  ').convert(data);
    final path = await _getFilePath('collection', 'json');
    await File(path).writeAsString(jsonString);
    return path;
  }

  // ==========================================
  // CSV Export
  // ==========================================

  Future<String> _exportCsv(List<Album> albums) async {
    final rows = <List<String>>[
      // Header
      ['Title', 'Artist', 'Year', 'Genre', 'Label', 'Barcode', 'MusicBrainz ID', 'Tracklist', 'Date Added'],
    ];

    for (final album in albums) {
      rows.add([
        album.title,
        album.artist,
        album.year?.toString() ?? '',
        album.genre ?? '',
        album.label ?? '',
        album.barcode ?? '',
        album.musicBrainzId ?? '',
        album.tracklist.join('; '),
        album.dateAdded.toIso8601String(),
      ]);
    }

    final csvString = const ListToCsvConverter().convert(rows);
    final path = await _getFilePath('collection', 'csv');
    await File(path).writeAsString(csvString);
    return path;
  }

  // ==========================================
  // PDF Export
  // ==========================================

  Future<String> _exportPdf(List<Album> albums) async {
    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(
        base: pw.Font.helvetica(),
        bold: pw.Font.helveticaBold(),
      ),
    );

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => pw.Container(
          padding: const pw.EdgeInsets.only(bottom: 10),
          decoration: const pw.BoxDecoration(
            border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300)),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Album Collection',
                style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
              ),
              pw.Text(
                '\${albums.length} albums',
                style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
              ),
            ],
          ),
        ),
        build: (context) {
          return [
            pw.SizedBox(height: 10),
            ...albums.map((album) => _buildAlbumRow(album)),
          ];
        },
        footer: (context) => pw.Container(
          padding: const pw.EdgeInsets.only(top: 10),
          decoration: const pw.BoxDecoration(
            border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300)),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Album Scanner',
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey400),
              ),
              pw.Text(
                'Page \${context.pageNumber}',
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey400),
              ),
            ],
          ),
        ),
      ),
    );

    final path = await _getFilePath('collection', 'pdf');
    final file = File(path);
    await file.writeAsBytes(await pdf.save());
    return path;
  }

  pw.Widget _buildAlbumRow(Album album) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(vertical: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey200, width: 0.5)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Expanded(
                child: pw.Text(
                  '\${album.artist} - \${album.title}',
                  style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold),
                ),
              ),
              if (album.year != null)
                pw.Text(
                  album.year.toString(),
                  style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
                ),
            ],
          ),
          if (album.genre != null || album.label != null)
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 2),
              child: pw.Text(
                [album.genre, album.label].where((e) => e != null).join(' | '),
                style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
              ),
            ),
          if (album.tracklist.isNotEmpty)
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 4),
              child: pw.Text(
                album.tracklist.asMap().entries.map((e) => '\${e.key + 1}. \${e.value}').join(', '),
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey400),
                maxLines: 2,
              ),
            ),
        ],
      ),
    );
  }

  // ==========================================
  // Helpers
  // ==========================================

  Map<String, dynamic> _albumToMap(Album album) => {
        'id': album.id,
        'title': album.title,
        'artist': album.artist,
        'year': album.year,
        'genre': album.genre,
        'label': album.label,
        'barcode': album.barcode,
        'musicBrainzId': album.musicBrainzId,
        'tracklist': album.tracklist,
        'dateAdded': album.dateAdded.toIso8601String(),
        'confidence': album.recognitionConfidence,
      };

  Future<String> _getFilePath(String prefix, String extension) async {
    final dir = await getTemporaryDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    return '\${dir.path}/\${prefix}_\$timestamp.\$extension';
  }
}
